### ISSUE TITLE
Crux links are broken in docs

### ISSUE THREAD

**Issue by naomijub** [naomijub/transistor#37]
**Describe the bug**
Crux docs links are broken due to current Crux docs update (https://opencrux.com/reference/get-started.html)

**Expected behavior**
links changed from https://opencrux.com/docs to  https://opencrux.com/reference

**Comment by naomijub** [comment]
https://github.com/naomijub/transistor/pull/42

**Comment by otaviopace** [comment]
Shoudn't this be closed?
