### ISSUE TITLE
Change CI to CircleCI

### ISSUE THREAD

**Issue by naomijub** [naomijub/transistor#53]
**Is your feature request related to a problem or issue? Please describe or annex.**
Travis CI is too buggy

**Purpose the solution you'd like**
Change to CircleCI

**Describe alternatives you've considered**

**Additional context**
Our PRs always fail due to test problems in Travis CI

**Comment by PurpleMyst** [comment]
I'm working on this.

**Comment by naomijub** [comment]
@PurpleMyst if you prefer you can work from the beta https://github.com/naomijub/transistor/pull/57
