### ISSUE TITLE
Implement tx-log MATCH

### ISSUE THREAD

**Issue by naomijub** [naomijub/transistor#6]
https://opencrux.com/docs#transactions-match

There should be a trait `TxLogMatch` that when implemented reads the `id` field containing a `CruxId` and receives an edn containing the map of properties and values to be checked:

* The `PUT`:  `[:crux.tx/put { :crux.db/id :jorge-3, :first-name "Michael", :last-name "Jorge", }]`.

The `MATCH`:
```
[:crux.tx/match
  :jorge-3
 {:first-name "Michael"}]
```

**Comment by naomijub** [comment]
@otaviopace

**Comment by otaviopace** [comment]
Why will this need macros? I think I didn't get it yet 🤔

**Comment by naomijub** [comment]
Guess this was prior to returning Raw Edns...
Can I close it?

**Comment by naomijub** [comment]
The idea was to convert the `{...}` directly into the struct having a response type like this:
```rust
struct MatchResponse<T: Deserialize> {
  id: CruxId,
  body: T
}
```

**Comment by naomijub** [comment]
`Match` doesn't seem to work for Docker Crux
