### ISSUE TITLE
`entity_tx` panics if the id provided is non-existent

### ISSUE THREAD

**Issue by jarhodes314** [naomijub/transistor#64]
Currently if I do something like:

```rust
let client = Crux::new("crux", "3000").http_client();
let tx_body = client.entity_tx(CruxId::new("unknown-id-here"))
```

It panics with 'called `Result::unwrap()` on an `Err` value: ParseError(Invalid)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/transistor-2.0.0/src/types/response.rs:135:74'.

A request to `http://crux:3000/entity-tx` with `{:eid :unknown-id-here}` will respond with a status of `404` and a body of `nil`, which should probably be handled gracefully with an error rather than panicking.

**Comment by naomijub** [comment]
I will take a look, thanks

**Comment by naomijub** [comment]
PR is merged for this issue, as soon as I have time I will take a look at issue #66  that is related
